[package]
name = "minecraft-server-utils"
version = "1.0.0"
edition = "2024"

[dependencies]
cursive = {version = "0.21", features = ["toml"]}
reqwest = { version = "0.12.20", features = ["blocking"]}
serde_json = "1.0.140"
serde = {version = "1.0.219", features = ["derive"] }
